export default {
  lang: {
    placeholder: 'Select date',
    rangePlaceholder: [
      'Start date',
      'End date',
    ],
    today: '今天',
    now: '现在',
    backToToday: '返回到今天',
    ok: '确认',
    clear: '清除',
    month: '月',
    year: '年',
    timeSelect: '请选择时间',
    dateSelect: '请选择日期',
    monthSelect: 'Choose a month',
    yearSelect: 'Choose a year',
    decadeSelect: 'Choose a decade',
    yearFormat: 'YYYY',
    dateFormat: 'M/D/YYYY',
    dayFormat: 'D',
    dateTimeFormat: 'M/D/YYYY HH:mm:ss',
    monthFormat: 'MMMM',
    monthBeforeYear: true,
    previousMonth: 'Previous month (PageUp)',
    nextMonth: 'Next month (PageDown)',
    previousYear: 'Last year (Control + left)',
    nextYear: 'Next year (Control + right)',
    previousDecade: 'Last decade',
    nextDecade: 'Next decade',
    previousCentury: 'Last century',
    nextCentury: 'Next century',
  },
  timePickerLocale: {
    placeholder: 'Select time',
  },
};
